version: '3'
services:
  sql-study-postgres:
    container_name: sql-study-postgres
    build:
      context: ./postgres/
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  sql-study-postgres2:
    container_name: sql-study-postgres2
    build:
      context: ./postgres2/
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres2_data:/var/lib/postgresql/data
  sql-study-postgres3:
    container_name: sql-study-postgres3
    build:
      context: ./postgres3/
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres3_data:/var/lib/postgresql/data
  sql-study-pad:
    image: sqlpad/sqlpad:5
    hostname: 'sqlpad'
    ports:
      - '3000:3000'
    environment:
      SQLPAD_ADMIN: admin@sqlpad.com
      SQLPAD_ADMIN_PASSWORD: password
      SQLPAD_APP_LOG_LEVEL: debug
      SQLPAD_WEB_LOG_LEVEL: warn
      SQLPAD_SEED_DATA_PATH: /etc/sqlpad/seed-data
    volumes:
      - ./seed-data:/etc/sqlpad/seed-data
      - ./sqlpad_data:/var/lib/sqlpad
